### ISSUE TITLE
TheForm.vue 太過龐雜，應改善

### ISSUE THREAD

**Issue by yunningtseng** [yunningtseng/practice-form#1]
TheForm.vue 目前有 400 多行，有幾個改進的想法：

1. 或許可以把資料庫請求抽出到 databaseOperation.js
2. questionMap 可以直接存在資料庫，並從資料庫提取

**Comment by Jenniferwyqq** [comment]
Please review, just added a frame of database connected for this issue.
Thank you.

**Comment by yunningtseng** [comment]
> Please review, just added a frame of database connected for this issue.
> Thank you.

我會參考
